spring:
  datasource:
    url: jdbc:mysql://localhost/fantacalcio_user?useLegacyDatetimeCode=false&serverTimezone=Etc/UTC
    username: fantacalcio_db_user
    password: fantacalciodbpass1
    driverClassName: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8070